### PR TITLE
Merge common code between ALEX_MONAD and ALEX_MONAD_BYTESTRING

### PR DESCRIPTION
**Pull request by josephcsible**

### CODE REVIEW

**Comment by simonmar** [comment]
This looks ok, but could you rebase and update the PR now that I've fixed the CI failure?

**Comment by josephcsible** [comment]
Done.

**Comment by hvr** [comment]
@simonmar given in the past seemingly harmless changes to the templates turned out to break consumers of the generated alex parsers; please let's very careful in testing this before so we don't have to schedule in overtime hours for Hackage Trustees to fixup up versions bounds of `build-tool-depends` all over hackage :-)

**Comment by simonmar** [comment]
@hvr thanks for the heads up. I wasn't aware of the previous problems. What kind of testing would be appropriate?

**Pull request merged**
